services:
  database:
    image: mongo:8.0.4-noble
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes: 
      - db:/var/lib/mongo/data
    restart: always
    
  backend:
    build: 
      context: ./backend
    ports: 
      - 3100:3100
    environment:
      PORT: 3100
      API_KEY: d06668cb-d50c-4732-ac5f-b0275acecbf2
      DATABASE_URL: mongodb://admin:admin@database:27017
    restart: always

  frontend:
    build: 
      context: ./frontend
      args:
        BACKEND_URL: http://localhost:3100
    ports: 
      - 3200:3200
    restart: always

volumes:
  db:
    driver: local