name: Deploy to Docker Hub

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and Push backend
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:backend"
          tags: mithosk/checkifly-backend:${{ github.run_number }}

      - name: Build and Push frontend
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:frontend"
          tags: mithosk/checkifly-frontend:${{ github.run_number }}